version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: clouddrop_postgres
    environment:
      POSTGRES_USER: chukwudinwodi
      POSTGRES_DB: clouddrop
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    volumes:
      - clouddrop_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  clouddrop_pgdata:
